# This is a basic workflow to help you get started with Actions


name: Upload to COS

on: [push]

jobs:
# 执行build
  build:
    runs-on: ubuntu-latest
#   自动化步骤
    steps:
    - uses: actions/checkout@v2
    - name: Install coscmd
      run: sudo pip install coscmd
    - name: install and build
      run: 
          npm install
          npm run build      
  # Deploy
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN  }}
        ARGS: "-avz --delete"
        SOURCE: "docs/.vuepress/dist"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET }}

