# This is a basic workflow to help you get started with Actions


name: Upload to COS

on: [push]

jobs:
# 执行build
  build:
    runs-on: ubuntu-latest
#   自动化步骤
    steps:
    - uses: actions/checkout@v2
    - name: Install coscmd
      run: sudo pip install coscmd
    - name: install and build
      run: 
          npm install
          npm run build
    - name: Configure coscmd
#     配置服务器密钥
      env:
        SECRET_ID: ${{ secrets.SecretId }}
        SECRET_KEY: ${{ secrets.SecretKey }}
        BUCKET: docs-1258965673
        REGION: ap-shanghai
        LOCAL_DIR: docs/.vuepress/dist
        REMOTE_DIR: /
      run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
    - name: Upload
      run: coscmd upload -rs --delete -f ./dist/* / --ignore "./.git/*"
      


